### ISSUE TITLE
NA not accepted

### ISSUE THREAD

**Issue by nehiljain** [jdstorey/qvalue#3]
When I use the package to calculate qvalues. The `min < 0 & max > 1` condition throws an error when it get NA values in the p value vector.

[r p.adjust](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html) allows NA values. This should be added to this package.

Thanks :smiley:

**Comment by ajbass** [comment]
This is important- thanks for pointing it out! I just fixed it so the following functions handle NA values:

* `qvalue`
* `lfdr`
* `pi0est`

Let me know if it works out,
Andy
